[package]
name = "bevy-vehicle-template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
bevy_panorbit_camera = "0.19.3"
bevy_rapier3d = "0.27"
bevy_infinite_grid = "0.13.0"
bevy_third_person_camera = "0.1.11"
